dpublication.publication_type.*:
  type: config_entity
  label: 'Publication type'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
    publicationPageType:
      type: string
      label: 'Publication page type'

dpublication.publication_page_type.*:
  type: config_entity
  label: 'Publication page type'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'

field.widget.settings.publication_page_title:
  type: mapping
  label: 'Publication page title widget settings'
  mapping:
    always_show:
      type: boolean
      label: 'Status display a field'

field.formatter.settings.dpublication_pages:
  type: mapping
  label: 'Publication pages field formatter settings'
  mapping:
    override_field_label:
      type: boolean
      label: 'Status for override field label'
    label:
      type: label
      label: 'New field label'
